# Generated by Django 4.1.7 on 2023-03-18 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dk_info', '0002_component_primary_datasheet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='detailed_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='order_unit_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='product_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='usual_order_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='component',
            name='cache_expiry',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 3, 18, 17, 5, 53, 941331, tzinfo=datetime.timezone.utc)),
        ),
    ]
