# Generated by Django 4.1.7 on 2023-03-18 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dk_info', '0007_rename__detailed_description_component_detailed_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='cache_expiry',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 3, 18, 18, 9, 6, 340598, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='component',
            name='resell_price',
            field=models.FloatField(null=True),
        ),
    ]
