# Generated by Django 4.1.7 on 2023-03-18 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dk_info', '0008_alter_component_cache_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='cache_expiry',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 3, 18, 18, 12, 22, 912780, tzinfo=datetime.timezone.utc)),
        ),
    ]
