# Generated by Django 4.1.7 on 2023-03-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dk_info', '0009_alter_component_cache_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='cache_expiry',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
