# Generated by Django 4.1.7 on 2023-03-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dk_info', '0010_alter_component_cache_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='resell_price',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
    ]
