# Generated by Django 4.1.7 on 2023-03-19 01:59

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dk_info', '0013_assortmentbox_merchant_purchase_storageunit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digikeycomponent',
            name='cache_expiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 1, 59, 17, 159298, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 1, 59, 17, 160346, tzinfo=datetime.timezone.utc)),
        ),
    ]
