# Generated by Django 4.1.7 on 2023-03-19 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dk_info', '0018_rename_dk_part_number_component_part_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageunit',
            name='storage_unit_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dk_info.storageunittype'),
        ),
    ]
