# Generated by Django 4.1.7 on 2023-03-19 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dk_info', '0026_componenttype_subcomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dk_info.componenttype'),
        ),
    ]
