# Generated by Django 4.1.7 on 2023-03-19 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dk_info', '0031_componenttype_id_alter_componenttype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dk_info.componenttype'),
        ),
    ]
