# Generated by Django 4.1.7 on 2023-03-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dk_info', '0035_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
