# Generated by Django 4.1.7 on 2023-03-19 22:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dk_info', '0039_remove_component_storage_unit_compartment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digikeycomponent',
            name='cache_expiry',
        ),
        migrations.AddField(
            model_name='component',
            name='cache_expiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
