# Generated by Django 4.1.7 on 2023-03-19 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dk_info', '0040_remove_digikeycomponent_cache_expiry_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DigiKeyComponent',
        ),
    ]
