# Generated by Django 4.1.7 on 2023-03-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dk_info', '0044_alter_component_primary_datasheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='part_number',
            field=models.CharField(max_length=64, verbose_name='Part number'),
        ),
    ]
