# Generated by Django 4.1.7 on 2023-03-21 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dk_info', '0046_rename_type_component_component_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcomponent',
            name='component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dk_info.component'),
        ),
    ]
