# Generated by Django 4.1.7 on 2023-03-21 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dk_info', '0047_subcomponent_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dk_info.component'),
        ),
    ]
