# Generated by Django 4.1.7 on 2023-03-18 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dk_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='primary_datasheet',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='cache_expiry',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 3, 18, 16, 48, 30, 785944, tzinfo=datetime.timezone.utc)),
        ),
    ]
