# Generated by Django 4.1.7 on 2023-03-18 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dk_info', '0003_component_detailed_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='detailed_description',
            new_name='_detailed_description',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='order_unit_price',
            new_name='_order_unit_price',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='primary_datasheet',
            new_name='_primary_datasheet',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='product_description',
            new_name='_product_description',
        ),
        migrations.AlterField(
            model_name='component',
            name='cache_expiry',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 3, 18, 17, 18, 10, 918856, tzinfo=datetime.timezone.utc)),
        ),
    ]
