# Generated by Django 4.1.7 on 2023-03-18 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dk_info', '0004_rename_detailed_description_component__detailed_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='id',
        ),
        migrations.AlterField(
            model_name='component',
            name='cache_expiry',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 3, 18, 17, 30, 44, 285291, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='component',
            name='dk_part_number',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
