# Generated by Django 4.1.7 on 2023-03-18 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dk_info', '0006_alter_component_cache_expiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='_detailed_description',
            new_name='detailed_description',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='_order_unit_price',
            new_name='order_unit_price',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='_primary_datasheet',
            new_name='primary_datasheet',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='_product_description',
            new_name='product_description',
        ),
        migrations.AlterField(
            model_name='component',
            name='cache_expiry',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 3, 18, 18, 6, 50, 51850, tzinfo=datetime.timezone.utc)),
        ),
    ]
