# Generated by Django 4.1.7 on 2023-03-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dk_info', '0011_alter_component_resell_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='detailed_description',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='primary_datasheet',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='product_description',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
