# Generated by Django 4.1.7 on 2023-03-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dk_info', '0015_alter_inventory_timestamp_alter_purchase_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='order_number',
            field=models.CharField(default='1', max_length=64),
            preserve_default=False,
        ),
    ]
