# Generated by Django 4.1.7 on 2023-03-19 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dk_info', '0017_rename_count_purchaseline_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='dk_part_number',
            new_name='part_number',
        ),
    ]
