# Generated by Django 4.1.7 on 2023-03-19 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dk_info', '0020_remove_storageunittype_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dk_info.merchant'),
        ),
    ]
