# Generated by Django 4.1.7 on 2023-03-19 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dk_info', '0024_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='storage_unit_compartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dk_info.storageunitcompartment'),
        ),
    ]
