# Generated by Django 4.1.7 on 2023-03-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dk_info', '0025_alter_component_storage_unit_compartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubComponent',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
    ]
