# Generated by Django 4.1.7 on 2023-03-19 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dk_info', '0029_subcomponent_id_alter_subcomponent_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='type',
        ),
    ]
