# Generated by Django 4.1.7 on 2023-03-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dk_info', '0033_remove_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
