# Generated by Django 4.1.7 on 2023-03-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dk_info', '0038_remove_component_storage_unit_compartment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='storage_unit_compartment',
        ),
        migrations.AddField(
            model_name='subcomponent',
            name='storage_unit_compartment',
            field=models.ManyToManyField(to='dk_info.storageunitcompartment'),
        ),
    ]
