# Generated by Django 4.1.7 on 2023-03-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dk_info', '0041_delete_digikeycomponent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='component',
        ),
        migrations.RemoveField(
            model_name='purchaseline',
            name='component',
        ),
        migrations.AddField(
            model_name='component',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='component',
            name='part_number',
            field=models.CharField(max_length=64),
        ),
    ]
