# Generated by Django 4.1.7 on 2023-03-19 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dk_info', '0042_remove_inventory_component_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='component',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dk_info.component'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='component',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dk_info.component'),
            preserve_default=False,
        ),
    ]
