# Generated by Django 4.1.7 on 2023-03-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dk_info', '0043_inventory_component_purchaseline_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='primary_datasheet',
            field=models.URLField(max_length=254, null=True),
        ),
    ]
