# Generated by Django 4.1.7 on 2023-03-23 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='component_type',
        ),
        migrations.RemoveField(
            model_name='component',
            name='order_unit_price',
        ),
        migrations.RemoveField(
            model_name='component',
            name='resell_price',
        ),
        migrations.AddField(
            model_name='subcomponent',
            name='component_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bts.componenttype'),
        ),
        migrations.AddField(
            model_name='subcomponent',
            name='order_unit_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcomponent',
            name='resell_price',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='detailed_description',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='primary_datasheet',
            field=models.URLField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='product_description',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='storageunittype',
            name='label_template',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subcomponent',
            name='storage_unit_compartment',
            field=models.ManyToManyField(blank=True, to='bts.storageunitcompartment'),
        ),
    ]
