# Generated by Django 4.1.7 on 2023-03-23 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0002_remove_component_component_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcomponent',
            name='storage_unit_compartment',
        ),
        migrations.CreateModel(
            name='SubComponentStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_unit_compartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bts.storageunitcompartment')),
                ('sub_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bts.subcomponent')),
            ],
        ),
        migrations.AddField(
            model_name='subcomponent',
            name='storage_unit_compartment_new',
            field=models.ManyToManyField(blank=True, through='bts.SubComponentStorage', to='bts.storageunitcompartment'),
        ),
    ]
