# Generated by Django 4.1.7 on 2023-03-23 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0004_rename_storage_unit_compartment_new_subcomponent_storage_unit_compartment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcomponent',
            old_name='storage_unit_compartment',
            new_name='storage_unit_compartments',
        ),
    ]
