# Generated by Django 4.1.7 on 2023-03-23 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0006_remove_subcomponent_storage_unit_compartments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='component',
        ),
        migrations.AddField(
            model_name='inventory',
            name='storage_unit_compartment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bts.storageunitcompartment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='sub_component',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bts.subcomponent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcomponent',
            name='storage_unit_compartments',
            field=models.ManyToManyField(blank=True, through='bts.Inventory', to='bts.storageunitcompartment'),
        ),
        migrations.DeleteModel(
            name='SubComponentStorage',
        ),
    ]
