# Generated by Django 4.1.7 on 2023-04-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0008_alter_inventory_storage_unit_compartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assortmentbox',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='componenttype',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='storageunittype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('sub_component', 'storage_unit_compartment')},
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('merchant', 'order_number')},
        ),
        migrations.AlterUniqueTogether(
            name='storageunit',
            unique_together={('number', 'assortment_box')},
        ),
        migrations.AlterUniqueTogether(
            name='storageunitcompartment',
            unique_together={('name', 'storage_unit')},
        ),
        migrations.AlterUniqueTogether(
            name='subcomponent',
            unique_together={('name', 'component')},
        ),
    ]
