# Generated by Django 4.1.7 on 2023-04-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0009_alter_assortmentbox_name_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
