# Generated by Django 4.1.7 on 2023-04-13 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0010_component_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assortmentbox',
            options={'verbose_name_plural': 'assortment boxes'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'invetories'},
        ),
    ]
