# Generated by Django 4.1.7 on 2023-04-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0011_alter_assortmentbox_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storageunit',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='storageunit',
            constraint=models.UniqueConstraint(fields=('number', 'assortment_box'), name='UQ_StorageUnit_number_assortment_box'),
        ),
    ]
