# Generated by Django 4.1.7 on 2023-04-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0012_alter_storageunit_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storageunitcompartment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='storageunitcompartment',
            constraint=models.UniqueConstraint(fields=('name', 'storage_unit'), name='UQ_StorageUnitCompartment_name_storage_unit'),
        ),
    ]
