# Generated by Django 4.1.7 on 2023-04-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0014_alter_component_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcomponent',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='subcomponent',
            constraint=models.UniqueConstraint(fields=('name', 'component'), name='UQ_SubComponent_name_component'),
        ),
    ]
