# Generated by Django 4.1.7 on 2023-04-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0015_alter_subcomponent_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('sub_component', 'storage_unit_compartment'), name='UQ_Inventory_sub_component_storage_unit_compartment'),
        ),
    ]
