# Generated by Django 4.1.7 on 2023-04-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0017_alter_purchase_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageunitcompartment',
            name='z_index',
            field=models.IntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name='storageunitcompartment',
            constraint=models.UniqueConstraint(fields=('z_index', 'storage_unit'), name='UQ_StorageUnitCompartment_z_index_storage_unit'),
        ),
    ]
