# Generated by Django 4.1.7 on 2023-04-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0018_storageunitcompartment_z_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assortmentbox',
            name='label_type',
            field=models.CharField(default='hornbach', max_length=255),
            preserve_default=False,
        ),
    ]
