# Generated by Django 4.1.7 on 2023-04-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0019_assortmentbox_label_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='exact_match',
            field=models.BooleanField(default=True, help_text='Is this the actual SubComponent, or is it just one with similar enogh specs?'),
        ),
    ]
