# Generated by Django 4.1.7 on 2023-04-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0020_inventory_exact_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageunitcompartment',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
