# Generated by Django 4.1.7 on 2023-04-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0021_storageunitcompartment_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storageunitcompartment',
            old_name='description',
            new_name='labeltext',
        ),
    ]
