# Generated by Django 4.1.7 on 2023-04-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0022_rename_description_storageunitcompartment_labeltext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='exact_match',
            field=models.BooleanField(default=True, help_text='Is this the actual SubComponent, or is it just one with similar enough specs?'),
        ),
        migrations.AlterField(
            model_name='storageunitcompartment',
            name='labeltext',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
