# Generated by Django 4.1.7 on 2023-04-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0023_alter_inventory_exact_match_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
