# Generated by Django 4.1.7 on 2023-04-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0024_alter_merchant_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
