# Generated by Django 4.1.7 on 2023-04-19 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0025_merchant_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assortmentbox',
            options={'ordering': ['name'], 'verbose_name_plural': 'assortment boxes'},
        ),
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['product_description', 'merchant']},
        ),
        migrations.AlterModelOptions(
            name='componenttype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['storage_unit_compartment', 'sub_component'], 'verbose_name_plural': 'invetories'},
        ),
        migrations.AlterModelOptions(
            name='merchant',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['merchant', 'timestamp']},
        ),
        migrations.AlterModelOptions(
            name='purchaseline',
            options={'ordering': ['purchase', 'component']},
        ),
        migrations.AlterModelOptions(
            name='storageunit',
            options={'ordering': ['assortment_box', 'number']},
        ),
        migrations.AlterModelOptions(
            name='storageunitcompartment',
            options={'ordering': ['storage_unit', 'z_index']},
        ),
        migrations.AlterModelOptions(
            name='storageunittype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='subcomponent',
            options={'ordering': ['component', 'name']},
        ),
    ]
