# Generated by Django 4.1.7 on 2023-04-28 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0026_alter_assortmentbox_options_alter_component_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='assortmentbox',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assortmentbox',
            name='coordinates',
            field=models.CharField(blank=True, help_text='Spreadsheet style coordinates (e.g. A1, B5, ...)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assortmentbox',
            name='layout',
            field=models.CharField(blank=True, help_text='Layout of the storage units in the assortment box in columns and rows (e.g. 5x12, 5x12+2x3+1, ...)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assortmentbox',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bts.location'),
        ),
    ]
