# Generated by Django 4.2.1 on 2023-05-21 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0028_labeltype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assortmentbox',
            name='label_type',
        ),
    ]
