# Generated by Django 4.2.1 on 2023-05-26 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0029_remove_assortmentbox_label_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
