# Generated by Django 4.2.1 on 2023-05-26 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0031_remove_storageunittype_label_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageunittype',
            name='label_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bts.labeltype'),
        ),
    ]
