# Generated by Django 4.2.1 on 2023-05-28 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0032_storageunittype_label_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['storage_unit_compartment', 'sub_component'], 'verbose_name_plural': 'inventories'},
        ),
    ]
